### PR TITLE
fix: siber closing when clicked in logo

### LINKED ISSUE #970: fix: sidebar should close when logo is clicked
## Description

the sidebar does not behave as expected when clicking on the logo. If the closeOnSelect property is true, it must call logoAction and close the sidebar

## Expected Behavior

If the closeOnSelect property is set as true, it must close the sidebar when clicking on an option or logo.

## Current Behavior

It calls the logoAction but doesn't close the sidebar

## Screenshots
[Gravação de tela de 2023-12-01 09-18-53.webm](https://github.com/Brisanet/ion/assets/138057627/09946169-12d5-45b5-9e13-889cb240db0f)

### PR DESCRIPTION
**Pull request by larissa-kamily-brisa**
## Issue Number

fix #970 

## Description

Now the sidebar has the expected behavior. When clicked on the logo and the closeOnSelect property is true. The sidebar calls the logoAction and closes the sidebar.

## Screenshots
[Gravação de tela de 2023-12-01 11-36-14.webm](https://github.com/Brisanet/ion/assets/138057627/404f5843-dc56-4713-8789-6211284f60da)

## Compliance

- [x] I have verified that this change complies with our code and contribution policies.
- [x] I have verified that this change does not cause regressions and does not affect other parts of the code.

### CODE REVIEW

File: projects/ion/src/lib/sidebar/sidebar.component.ts [hunk 1]
```diff
@@ -58,4 +58,14 @@ export class IonSidebarComponent {
...
   }
+
+  public handleLogoClick(): void {
+    if (this.logoAction) {
+      this.logoAction();
+    }
+
+    if (this.closeOnSelect) {
+      this.toggleSidebarVisibility();
+    }
```
Comment (iurynogueira) [inline projects/ion/src/lib/sidebar/sidebar.component.ts:69]: If the 2 actions can be run, LGTM.

**Review by iurynogueira — APPROVED** [review]

File: projects/ion/src/lib/sidebar/sidebar.component.ts (hunk 1 above)
Comment (larissa-kamily-brisa) [reply projects/ion/src/lib/sidebar/sidebar.component.ts:69]: I've made a build and tested in caná project, it worked just fine redirecting and closing after :smile: 

[Gravação de tela de 2023-12-01 12-53-55.webm](https://github.com/Brisanet/ion/assets/138057627/352ea10b-4478-4a24-89b1-656161214b2d)

Comment (iurynogueira) [reply projects/ion/src/lib/sidebar/sidebar.component.ts:69]: LGTM.

**Review by allan-chagas-brisa — APPROVED** [review]
