### PR TITLE
refactor: fixing style error occurring in certain chip flows #926

### LINKED ISSUE #926: fix: Chip style malfunction when clicking outside of it to close the dropdown
## Description

The chip component with dropdown is having a problem with its style. The problem occurs when the chip is clicked and receives the selected style, when clicking elsewhere on the screen to close the dropdown the chip is maintaining the selected style. 

When the chip is initialized with a mandatory option it always shows the badge. Since the chip will always only have one option selected, there would be no need to show the badge.

## Expected Behavior

It is expected that when clicking elsewhere on the screen the chip will return to the original style.

Required chip dont show badge with the number of options.

## Current Behavior

With the chip open, when clicking elsewhere on the screen, it maintains the selected style.

Required chip always showing the badge

## Steps to Reproduce

Click on the chip to open the dropdown, then click elsewhere on the screen to close it.

## Screenshots

Steps to the first problem
Chip initial state:
image

Chip clicked:
image

After clicking outside the chip:
image

### PR DESCRIPTION
**Pull request by lucas-alcantara-brisa**
## 926

fix #926 

## Description

Adding functionality so that when a chip has a dropdown and it is closed, the chip now loses its selected style. Fixed both on the chip and on the chip group

## Proposed Changes

- In the event of closing the dropdown, the process to remove the style (chip.component)
- Chip now emits, in its events, when the dropdown is closed. Change necessary to fix the problem in the chip-group3
- Chip-group now have the function to clear the chip selecteds when the dropdown-close event is emmited

## How to Test

Open the chip dropdown and then click outside the component

### CODE REVIEW

File: projects/ion/src/lib/chip-group/chip-group.component.ts [hunk 1]
```diff
@@ -65,6 +66,12 @@ export class IonChipGroupComponent {
     }
   }
 
+  chipEvents(event: ChipEvent) {
```
Comment (allan-chagas-brisa) [inline projects/ion/src/lib/chip-group/chip-group.component.ts:69]:
```suggestion
  chipEvents(event: ChipEvent): void {
```

**Review by allan-chagas-brisa — APPROVED** [review]

File: projects/ion/src/lib/chip-group/chip-group.component.html [hunk 2]
```diff
@@ -6,6 +6,7 @@
     [disabled]="chip.disabled || disabled"
     [selected]="chip.selected"
     [showDropdown]="chip.selected && chip.options"
+    [showToggle]="true"
```
Comment (alysson-mascarenhas-brisa) [inline projects/ion/src/lib/chip-group/chip-group.component.html:9]: Shouldn't this property be optional?

**Review by alysson-mascarenhas-brisa — APPROVED** [review]

File: projects/ion/src/lib/chip-group/chip-group.component.html (hunk 2 above)
Comment (allan-chagas-brisa) [reply projects/ion/src/lib/chip-group/chip-group.component.html:9]: I don't think so, because it wont add any wanted behavior to the chip group, it was only added so it could make the chip with dropdown work as expected. But if we have a case I can set this as a variable property.
